### ISSUE TITLE
Nice discord token grabber bro :)

### ISSUE THREAD

**Issue by CookieClientDEV** [EzyLw/Pixel-Fondation-Motox#1]
His discord **webhook** 👍 ```

⬇

`https://discordapp.com/api/webhooks/867773840662462504/c2YU2335Mxdn83rvqRB3i5_-pJD7SBO91IQ1gcMLhc3mnwQZUgoX6E6RF1trmD8U-APY`

**Comment by FuchsPlayZ** [comment]
I Agree. Nice try. But sadly, too easily decompiled. Maybe try encrypting?

**Comment by CookieClientDEV** [comment]
> I Agree. Nice try. But sadly, too easily decompiled. Maybe try encrypting?

well, do you think an 8-year-old child can do that? xD
